Make esound optional (only build driver if present)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -701,6 +701,10 @@ host_os
 PKG_CONFIG
 PACKAGE_CFLAGS
 PACKAGE_LIBS
+ESOUND_CFLAGS
+ESOUND_LIBS
+AUDIO_ESOUND_TRUE
+AUDIO_ESOUND_FALSE
 BUILD_SH4X86_TRUE
 BUILD_SH4X86_FALSE
 CDROM_LINUX_TRUE
@@ -745,7 +749,9 @@ CPPFLAGS
 CPP
 PKG_CONFIG
 PACKAGE_CFLAGS
-PACKAGE_LIBS'
+PACKAGE_LIBS
+ESOUND_CFLAGS
+ESOUND_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1342,6 +1348,9 @@ Some influential environment variables:
               C compiler flags for PACKAGE, overriding pkg-config
   PACKAGE_LIBS
               linker flags for PACKAGE, overriding pkg-config
+  ESOUND_CFLAGS
+              C compiler flags for ESOUND, overriding pkg-config
+  ESOUND_LIBS linker flags for ESOUND, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5056,12 +5065,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_PACKAGE_CFLAGS="$PACKAGE_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" gtk+-2.0      esound      libpng \"") >&5
-  ($PKG_CONFIG --exists --print-errors " gtk+-2.0      esound      libpng ") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" gtk+-2.0      libpng \"") >&5
+  ($PKG_CONFIG --exists --print-errors " gtk+-2.0      libpng ") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_PACKAGE_CFLAGS=`$PKG_CONFIG --cflags " gtk+-2.0      esound      libpng " 2>/dev/null`
+  pkg_cv_PACKAGE_CFLAGS=`$PKG_CONFIG --cflags " gtk+-2.0      libpng " 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -5074,12 +5083,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_PACKAGE_LIBS="$PACKAGE_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" gtk+-2.0      esound      libpng \"") >&5
-  ($PKG_CONFIG --exists --print-errors " gtk+-2.0      esound      libpng ") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" gtk+-2.0      libpng \"") >&5
+  ($PKG_CONFIG --exists --print-errors " gtk+-2.0      libpng ") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_PACKAGE_LIBS=`$PKG_CONFIG --libs " gtk+-2.0      esound      libpng " 2>/dev/null`
+  pkg_cv_PACKAGE_LIBS=`$PKG_CONFIG --libs " gtk+-2.0      libpng " 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -5098,14 +5107,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors " gtk+-2.0      esound      libpng "`
+	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors " gtk+-2.0      libpng "`
         else
-	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " gtk+-2.0      esound      libpng "`
+	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " gtk+-2.0      libpng "`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$PACKAGE_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements ( gtk+-2.0      esound      libpng ) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements ( gtk+-2.0      libpng ) were not met:
 
 $PACKAGE_PKG_ERRORS
 
@@ -5116,7 +5125,7 @@ Alternatively, you may set the environment variables PACKAGE_CFLAGS
 and PACKAGE_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements ( gtk+-2.0      esound      libpng ) were not met:
+echo "$as_me: error: Package requirements ( gtk+-2.0      libpng ) were not met:
 
 $PACKAGE_PKG_ERRORS
 
@@ -5157,6 +5166,92 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for ESOUND" >&5
+echo $ECHO_N "checking for ESOUND... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$ESOUND_CFLAGS"; then
+        pkg_cv_ESOUND_CFLAGS="$ESOUND_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"esound\"") >&5
+  ($PKG_CONFIG --exists --print-errors "esound") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_ESOUND_CFLAGS=`$PKG_CONFIG --cflags "esound" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$ESOUND_LIBS"; then
+        pkg_cv_ESOUND_LIBS="$ESOUND_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"esound\"") >&5
+  ($PKG_CONFIG --exists --print-errors "esound") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_ESOUND_LIBS=`$PKG_CONFIG --libs "esound" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        ESOUND_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "esound"`
+        else
+	        ESOUND_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "esound"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$ESOUND_PKG_ERRORS" >&5
+
+	 echo "Warning: esound not found - building without audio support"
+elif test $pkg_failed = untried; then
+	 echo "Warning: esound not found - building without audio support"
+else
+	ESOUND_CFLAGS=$pkg_cv_ESOUND_CFLAGS
+	ESOUND_LIBS=$pkg_cv_ESOUND_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+     HAVE_ESOUND='yes'
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ESOUND 1
+_ACEOF
+
+fi
+
+
+if test "$HAVE_ESOUND" = 'yes' ; then
+  AUDIO_ESOUND_TRUE=
+  AUDIO_ESOUND_FALSE='#'
+else
+  AUDIO_ESOUND_TRUE='#'
+  AUDIO_ESOUND_FALSE=
+fi
+
+
 
 { echo "$as_me:$LINENO: checking for uncompress in -lz" >&5
 echo $ECHO_N "checking for uncompress in -lz... $ECHO_C" >&6; }
@@ -5959,6 +6054,7 @@ fi
 
 
 GETTEXT_PACKAGE=lxdream
+
 
 cat >>confdefs.h <<_ACEOF
 #define GETTEXT_PACKAGE "$GETTEXT_PACKAGE"
@@ -7583,6 +7679,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${AUDIO_ESOUND_TRUE}" && test -z "${AUDIO_ESOUND_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"AUDIO_ESOUND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"AUDIO_ESOUND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_SH4X86_TRUE}" && test -z "${BUILD_SH4X86_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_SH4X86\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -8235,15 +8338,15 @@ host_os!$host_os$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 PACKAGE_CFLAGS!$PACKAGE_CFLAGS$ac_delim
 PACKAGE_LIBS!$PACKAGE_LIBS$ac_delim
+ESOUND_CFLAGS!$ESOUND_CFLAGS$ac_delim
+ESOUND_LIBS!$ESOUND_LIBS$ac_delim
+AUDIO_ESOUND_TRUE!$AUDIO_ESOUND_TRUE$ac_delim
+AUDIO_ESOUND_FALSE!$AUDIO_ESOUND_FALSE$ac_delim
 BUILD_SH4X86_TRUE!$BUILD_SH4X86_TRUE$ac_delim
 BUILD_SH4X86_FALSE!$BUILD_SH4X86_FALSE$ac_delim
 CDROM_LINUX_TRUE!$CDROM_LINUX_TRUE$ac_delim
 CDROM_LINUX_FALSE!$CDROM_LINUX_FALSE$ac_delim
 SHCC!$SHCC$ac_delim
-SHLD!$SHLD$ac_delim
-SHOBJCOPY!$SHOBJCOPY$ac_delim
-ARMCC!$ARMCC$ac_delim
-ARMLD!$ARMLD$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8285,6 +8388,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+SHLD!$SHLD$ac_delim
+SHOBJCOPY!$SHOBJCOPY$ac_delim
+ARMCC!$ARMCC$ac_delim
+ARMLD!$ARMLD$ac_delim
 ARMOBJCOPY!$ARMOBJCOPY$ac_delim
 BUILD_SYSTEST_TRUE!$BUILD_SYSTEST_TRUE$ac_delim
 BUILD_SYSTEST_FALSE!$BUILD_SYSTEST_FALSE$ac_delim
@@ -8310,7 +8417,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 27; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
