Add configure-time checks for fbo and shader functions in libGL (so linking doesn't fail on really old libGL implementations)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5973,6 +5973,274 @@ fi
 fi
 fi
 
+{ echo "$as_me:$LINENO: checking for glGenFramebuffersEXT" >&5
+echo $ECHO_N "checking for glGenFramebuffersEXT... $ECHO_C" >&6; }
+if test "${ac_cv_func_glGenFramebuffersEXT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define glGenFramebuffersEXT to an innocuous variant, in case <limits.h> declares glGenFramebuffersEXT.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define glGenFramebuffersEXT innocuous_glGenFramebuffersEXT
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char glGenFramebuffersEXT (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef glGenFramebuffersEXT
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char glGenFramebuffersEXT ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_glGenFramebuffersEXT || defined __stub___glGenFramebuffersEXT
+choke me
+#endif
+
+int
+main ()
+{
+return glGenFramebuffersEXT ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_glGenFramebuffersEXT=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_glGenFramebuffersEXT=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_glGenFramebuffersEXT" >&5
+echo "${ECHO_T}$ac_cv_func_glGenFramebuffersEXT" >&6; }
+if test $ac_cv_func_glGenFramebuffersEXT = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENGL_FBO 1
+_ACEOF
+
+fi
+
+{ echo "$as_me:$LINENO: checking for glCreateShader" >&5
+echo $ECHO_N "checking for glCreateShader... $ECHO_C" >&6; }
+if test "${ac_cv_func_glCreateShader+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define glCreateShader to an innocuous variant, in case <limits.h> declares glCreateShader.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define glCreateShader innocuous_glCreateShader
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char glCreateShader (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef glCreateShader
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char glCreateShader ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_glCreateShader || defined __stub___glCreateShader
+choke me
+#endif
+
+int
+main ()
+{
+return glCreateShader ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_glCreateShader=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_glCreateShader=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_glCreateShader" >&5
+echo "${ECHO_T}$ac_cv_func_glCreateShader" >&6; }
+if test $ac_cv_func_glCreateShader = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENGL_SHADER 1
+_ACEOF
+
+fi
+
+{ echo "$as_me:$LINENO: checking for glCreateShaderObjectARB" >&5
+echo $ECHO_N "checking for glCreateShaderObjectARB... $ECHO_C" >&6; }
+if test "${ac_cv_func_glCreateShaderObjectARB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define glCreateShaderObjectARB to an innocuous variant, in case <limits.h> declares glCreateShaderObjectARB.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define glCreateShaderObjectARB innocuous_glCreateShaderObjectARB
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char glCreateShaderObjectARB (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef glCreateShaderObjectARB
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char glCreateShaderObjectARB ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_glCreateShaderObjectARB || defined __stub___glCreateShaderObjectARB
+choke me
+#endif
+
+int
+main ()
+{
+return glCreateShaderObjectARB ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_glCreateShaderObjectARB=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_glCreateShaderObjectARB=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_glCreateShaderObjectARB" >&5
+echo "${ECHO_T}$ac_cv_func_glCreateShaderObjectARB" >&6; }
+if test $ac_cv_func_glCreateShaderObjectARB = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENGL_SHADER_ARB 1
+_ACEOF
+
+fi
+
+
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for GTK" >&5
