Test for presence of linux/cdrom.h at configure time, and only build the linux driver if it's found successfully

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -693,6 +693,8 @@ EGREP
 PKG_CONFIG
 PACKAGE_CFLAGS
 PACKAGE_LIBS
+CDROM_LINUX_TRUE
+CDROM_LINUX_FALSE
 GETTEXT_PACKAGE
 USE_NLS
 MSGFMT
@@ -5202,14 +5204,6 @@ else
 fi
 
 
-GETTEXT_PACKAGE=dream
-
-cat >>confdefs.h <<_ACEOF
-#define GETTEXT_PACKAGE "$GETTEXT_PACKAGE"
-_ACEOF
-
-
-ALL_LINGUAS=""
 # On IRIX 5.3, sys/types and inttypes.h are conflicting.
 
 
@@ -5279,6 +5273,158 @@ fi
 done
 
 
+if test "${ac_cv_header_linux_cdrom_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for linux/cdrom.h" >&5
+echo $ECHO_N "checking for linux/cdrom.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_cdrom_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_cdrom_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_cdrom_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking linux/cdrom.h usability" >&5
+echo $ECHO_N "checking linux/cdrom.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <linux/cdrom.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking linux/cdrom.h presence" >&5
+echo $ECHO_N "checking linux/cdrom.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/cdrom.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: linux/cdrom.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: linux/cdrom.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: linux/cdrom.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: linux/cdrom.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: linux/cdrom.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: linux/cdrom.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: linux/cdrom.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/cdrom.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: linux/cdrom.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for linux/cdrom.h" >&5
+echo $ECHO_N "checking for linux/cdrom.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_cdrom_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_linux_cdrom_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_cdrom_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_cdrom_h" >&6; }
+
+fi
+if test $ac_cv_header_linux_cdrom_h = yes; then
+  HAVE_LINUX_CDROM_H=yes
+else
+
+    echo "Linux CDROM support not found, building without it."
+fi
+
+
+
+
+if test "$HAVE_LINUX_CDROM_H" = "yes"; then
+  CDROM_LINUX_TRUE=
+  CDROM_LINUX_FALSE='#'
+else
+  CDROM_LINUX_TRUE='#'
+  CDROM_LINUX_FALSE=
+fi
+
+
+GETTEXT_PACKAGE=dream
+
+cat >>confdefs.h <<_ACEOF
+#define GETTEXT_PACKAGE "$GETTEXT_PACKAGE"
+_ACEOF
+
+
+ALL_LINGUAS=""
 
 
 for ac_header in locale.h
@@ -6893,6 +7039,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CDROM_LINUX_TRUE}" && test -z "${CDROM_LINUX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CDROM_LINUX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CDROM_LINUX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -7508,6 +7661,8 @@ EGREP!$EGREP$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 PACKAGE_CFLAGS!$PACKAGE_CFLAGS$ac_delim
 PACKAGE_LIBS!$PACKAGE_LIBS$ac_delim
+CDROM_LINUX_TRUE!$CDROM_LINUX_TRUE$ac_delim
+CDROM_LINUX_FALSE!$CDROM_LINUX_FALSE$ac_delim
 GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
 USE_NLS!$USE_NLS$ac_delim
 MSGFMT!$MSGFMT$ac_delim
@@ -7523,8 +7678,6 @@ PO_IN_DATADIR_TRUE!$PO_IN_DATADIR_TRUE$ac_delim
 PO_IN_DATADIR_FALSE!$PO_IN_DATADIR_FALSE$ac_delim
 POFILES!$POFILES$ac_delim
 POSUB!$POSUB$ac_delim
-MKINSTALLDIRS!$MKINSTALLDIRS$ac_delim
-LIBOBJS!$LIBOBJS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7566,10 +7719,12 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MKINSTALLDIRS!$MKINSTALLDIRS$ac_delim
+LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 1; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
