Bail out if libGL or zlib isn't found (they're somewhat compulsory)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5052,9 +5052,9 @@ fi
 
 
 
-{ echo "$as_me:$LINENO: checking for ucompress in -lz" >&5
-echo $ECHO_N "checking for ucompress in -lz... $ECHO_C" >&6; }
-if test "${ac_cv_lib_z_ucompress+set}" = set; then
+{ echo "$as_me:$LINENO: checking for uncompress in -lz" >&5
+echo $ECHO_N "checking for uncompress in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_uncompress+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -5072,11 +5072,11 @@ cat >>conftest.$ac_ext <<_ACEOF
 #ifdef __cplusplus
 extern "C"
 #endif
-char ucompress ();
+char uncompress ();
 int
 main ()
 {
-return ucompress ();
+return uncompress ();
   ;
   return 0;
 }
@@ -5099,27 +5099,31 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_z_ucompress=yes
+  ac_cv_lib_z_uncompress=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_z_ucompress=no
+	ac_cv_lib_z_uncompress=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_ucompress" >&5
-echo "${ECHO_T}$ac_cv_lib_z_ucompress" >&6; }
-if test $ac_cv_lib_z_ucompress = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_uncompress" >&5
+echo "${ECHO_T}$ac_cv_lib_z_uncompress" >&6; }
+if test $ac_cv_lib_z_uncompress = yes; then
   cat >>confdefs.h <<_ACEOF
 #define HAVE_LIBZ 1
 _ACEOF
 
   LIBS="-lz $LIBS"
 
+else
+
+    echo "Zlib (libz.so) could not be found, but is required."
+    exit 1
 fi
 
 
@@ -5191,6 +5195,10 @@ _ACEOF
 
   LIBS="-lGL $LIBS"
 
+else
+
+    echo "The OpenGL library (libGL.so) could not be found, but is required."
+    exit 1
 fi
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -17,8 +17,12 @@ PKG_CHECK_MODULES(PACKAGE,
 AC_SUBST(PACKAGE_CFLAGS)
 AC_SUBST(PACKAGE_LIBS)
 
-AC_CHECK_LIB(z, ucompress)
-AC_CHECK_LIB(GL, glXQueryVersion)
+AC_CHECK_LIB(z, uncompress, [], [
+    echo "Zlib (libz.so) could not be found, but is required."
+    exit 1])
+AC_CHECK_LIB(GL, glXQueryVersion, [], [
+    echo "The OpenGL library (libGL.so) could not be found, but is required."
+    exit 1])
 
 GETTEXT_PACKAGE=dream
 AC_SUBST(GETTEXT_PACKAGE)
