Add libpng as a dependency

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4947,12 +4947,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_PACKAGE_CFLAGS="$PACKAGE_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" libgnomeui-2.0      esound \"") >&5
-  ($PKG_CONFIG --exists --print-errors " libgnomeui-2.0      esound ") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" libgnomeui-2.0      esound      libpng \"") >&5
+  ($PKG_CONFIG --exists --print-errors " libgnomeui-2.0      esound      libpng ") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_PACKAGE_CFLAGS=`$PKG_CONFIG --cflags " libgnomeui-2.0      esound " 2>/dev/null`
+  pkg_cv_PACKAGE_CFLAGS=`$PKG_CONFIG --cflags " libgnomeui-2.0      esound      libpng " 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -4965,12 +4965,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_PACKAGE_LIBS="$PACKAGE_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" libgnomeui-2.0      esound \"") >&5
-  ($PKG_CONFIG --exists --print-errors " libgnomeui-2.0      esound ") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \" libgnomeui-2.0      esound      libpng \"") >&5
+  ($PKG_CONFIG --exists --print-errors " libgnomeui-2.0      esound      libpng ") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_PACKAGE_LIBS=`$PKG_CONFIG --libs " libgnomeui-2.0      esound " 2>/dev/null`
+  pkg_cv_PACKAGE_LIBS=`$PKG_CONFIG --libs " libgnomeui-2.0      esound      libpng " 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -4989,14 +4989,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors " libgnomeui-2.0      esound "`
+	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors " libgnomeui-2.0      esound      libpng "`
         else
-	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " libgnomeui-2.0      esound "`
+	        PACKAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " libgnomeui-2.0      esound      libpng "`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$PACKAGE_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements ( libgnomeui-2.0      esound ) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements ( libgnomeui-2.0      esound      libpng ) were not met:
 
 $PACKAGE_PKG_ERRORS
 
@@ -5007,7 +5007,7 @@ Alternatively, you may set the environment variables PACKAGE_CFLAGS
 and PACKAGE_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements ( libgnomeui-2.0      esound ) were not met:
+echo "$as_me: error: Package requirements ( libgnomeui-2.0      esound      libpng ) were not met:
 
 $PACKAGE_PKG_ERRORS
 
@@ -5050,6 +5050,77 @@ echo "${ECHO_T}yes" >&6; }
 fi
 
 
+
+
+{ echo "$as_me:$LINENO: checking for ucompress in -lz" >&5
+echo $ECHO_N "checking for ucompress in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_ucompress+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ucompress ();
+int
+main ()
+{
+return ucompress ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_ucompress=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_ucompress=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_ucompress" >&5
+echo "${ECHO_T}$ac_cv_lib_z_ucompress" >&6; }
+if test $ac_cv_lib_z_ucompress = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBZ 1
+_ACEOF
+
+  LIBS="-lz $LIBS"
+
+fi
 
 
 { echo "$as_me:$LINENO: checking for glXQueryVersion in -lGL" >&5
